# Generated by Django 2.2.6 on 2019-10-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='account',
            field=models.IntegerField(default=0),
        ),
    ]
